INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('bsmart','shopping', 18, 32, 7000.0, 14999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('bsmart','shopping', 18, 23, 15000.0, NULL);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('bsmart','mystyle', 18, 75, 7000.0, 14999.00);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('bsmart','mystyle', 18, 75, 35000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('bsmart','mystyle', 18, 32, 15000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Afinity Card','shopping', 18, 32, 7000.0, 14999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Afinity Card','shopping', 18, 23, 15000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Afinity Card','shopping', 24, 32, 15000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Afinity Card','mystyle', 18, 32, 7000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('clasica','shopping', 24, 75, 7000.0, 14999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Office Depot','shopping', 24, 75, 7000.0, 49999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Office Depot','mybusiness', 18, 75, 7000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Costco','shopping', 24, 75, 7000.0, 49999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Costco','mybusiness', 18, 75, 7000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Best Buy','shopping', 24, 75, 7000.0, 49999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Best Buy','mybusiness', 18, 75, 7000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('The Home Depot','shopping', 24, 75, 7000.0, 49999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('The Home Depot','mybusiness', 18, 75, 7000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Oro','shopping', 24, 75, 15000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Oro','mystyle', 24, 75, 15000.0, 29999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('platinum','mystyle', 24, 75, 30000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('platinum','travels', 22, 24, 50000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('platinum','shopping', 24, 75, 35000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Citi/AAdv','travels', 18, 75, 12000.0, 49999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('Citi/AAdv','travels', 18, 22, 50000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('APAC','help', 18, 75, 7000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('teleton','help', 18, 75, 7000.0, null);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('marti clasica','sports', 18, 75, 7000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('america','sports', 18, 75, 7000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('toluca','sports', 18, 75, 7000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('pumas','sports', 18, 75, 7000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('la verde','sports', 18, 75, 7000.0, 34999.0);
INSERT INTO datos.tarjetas(nombre, pasion, edad_minima, edad_maxima, sueldo_minimo, sueldo_maximo) VALUES ('marti premium','sports', 18, 75, 35000.0, null);